### ISSUE TITLE
Not able to print Japanese characters

### ISSUE THREAD

**Issue by Anagha589** [textlint-ja/analyze-desumasu-dearu#7]
downloaded this module on windows system and its not printing japanese characters.
Please help with other settings required. we are trying in Windows system.

**Comment by azu** [comment]
Do you have reproduce code?

**Comment by Anagha589** [comment]
we used below code after installing module but it didn't print 田中さん
var analyzeDesumasuDearu = require("analyze-desumasu-dearu")
console.log("た中さん");

**Comment by Anagha589** [comment]
we also used this code but does not work
"use strict";
const isDearu = require("analyze-desumasu-dearu").isDearu;
const isDesumasu = require("analyze-desumasu-dearu").isDesumasu;
const analyze = require("analyze-desumasu-dearu").analyze;
const analyzeDearu = require("analyze-desumasu-dearu").analyzeDearu;
const analyzeDesumasu = require("analyze-desumasu-dearu").analyzeDesumasu;
const text = "昨日はいい天気であったのだが、今日は悪天候です。";
analyze(text).then(results => {
    console.log("==である==");
    console.log(results.filter(isDearu));
    console.log("==ですます==");
    console.log(results.filter(isDesumasu));
});

**Comment by azu** [comment]
> we used below code after installing module but it didn't print 田中さん

It is strange...
This library does not hook `console` API.
Does other code work on your windows?

This library require following system.

- Node.js 6 >=
- npm 3 >=

**Comment by Anagha589** [comment]
we have node JS version 8.9.4 and npm version :5.6.0
did not understand what you meanby : This library does not hook console API.

we are running program from command prompt and written code on NotePad++

Please suggest !
